### ISSUE TITLE
Demo Content not loading

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#2] opened 2016-03-31 10:06 UTC
Demo Content is not loading:
Step 1:  go to sample demos select class 3 and click on "Even and Odd Numbers"
Step 2: it shows the loading content image but no content is loading only blank page displays. below are the image.

![image](https://cloud.githubusercontent.com/assets/16239450/14172442/b368a6fe-f755-11e5-8ddd-b5ee0756da1c.png)

![image](https://cloud.githubusercontent.com/assets/16239450/14172474/d68d5c2e-f755-11e5-802b-f4bae659aea6.png)

![image](https://cloud.githubusercontent.com/assets/16239450/14172493/eb45bcf6-f755-11e5-9ee6-9d4d875c2b3b.png)

**Comment by sumitmago** [comment] 2016-03-31 10:14
Hi, this same issue is raised twice earlier by me as well.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by sumitmago** [comment] 2016-04-01 06:18
this is duplicate of #1 hence closing it.

**Closed as completed by sumitmago** 2016-04-01 06:18 UTC
Labels: duplicate
